### ISSUE TITLE
代码问题

### ISSUE THREAD

**Issue by hzau96yhz** [EternityZY/STNSCM#1]
作者您好，main.py中`from model.STEGRN import STEGRN`代码有问题，model目录下并没有STEGRN

**Comment by EternityZY** [comment]
您好，感谢关注，将STEGRN替换成STNSCN即可，这里是笔误，之后我们会将其修复

**Comment by hzau96yhz** [comment]
感谢

**Comment by hzau96yhz** [comment]
还有个关于数据集的问题想请教您一下，您这里提供的数据集是npz格式的，请问原始数据集在哪里可以找到，因为是初次接触时空类型的任务，想参考一下这种数据集的形式。

**Comment by EternityZY** [comment]
我们使用的开源纽约花旗数据集 数据来源为https://citibikenyc.com/system-data
